server:
  port: 8081 # Puerto donde corre el auth-service (puedes ajustarlo)

logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

jackson:
    time-zone: America/Mexico_City # ← Aquí configuras la zona horaria local para JSON
jwt:
  secret: "YOGI_SUPER_SECRETA_CLAVE_32_CARACTERES_OMG123"
  expiration: 120000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true